'use client';

import { useMemo, useState } from 'react';
import plantData from './data/planten.json';
import zoneData from './data/tuin.json';

type Plant = (typeof plantData)[number];
type Zone = (typeof zoneData)[number];
type Tab = 'overzicht' | 'plattegrond' | 'vaktermen' | 'aanpassen' | 'pdfs';

const months = ['Januari','Februari','Maart','April','Mei','Juni','Juli','Augustus','September','Oktober','November','December'];
const monthShort = ['J','F','M','A','M','J','J','A','S','O','N','D'];
const functionLabels: Record<string,string> = { fruit:'Fruit',kruid:'Kruiden',insecten:'Insecten',vogel:'Vogels',sier:'Sier',boom:'Bomen',onkruid:'Onkruid' };
const functions = Object.keys(functionLabels);
const photoNames: Record<string,string> = {
  aardbei:'aardbei.jpg',azarooldoorn:'azarooldoorn.jpg',bieslook:'bieslook.jpg',bosbes:'bosbes.jpg',citroenmelisse:'citroenmelisse.jpg',dragon:'dragon.jpg','edel-duizendblad':'edel_duizendblad.JPG',framboos:'framboos.jpg',kardinaalmuts:'kardinaalsmuts.jpg',kiwi:'kiwi.JPEG',knopherik:'knopherik.jpg',lavendel:'Lavendel.jpg',marjolein:'marjolein.jpg',meidoorn:'meidoorn.jpg',munt:'munt.jpg','rode-bes':'rode_bes.JPG',rozemarijn:'rozemarijn.jpg',salie:'salie.jpg','spaanse-aak':'spaanse_aak.JPEG',teunisbloem:'teunisbloem.jpg',tijm:'Thyme.jpg',venkel:'venkel.jpg',wegedoorn:'wegedoorn.JPEG','witte-moerbei':'witte_moerbei.jpg','zwarte-bes':'zwarte bes.jpg'
};
const photo = (plant: Plant) => `/fotos/${encodeURIComponent(photoNames[plant.slug] || 'aardbei.jpg')}`;
const sortedPlants = [...plantData].sort((a,b)=>a.naam.localeCompare(b.naam,'nl'));

function Calendar({plant}:{plant:Plant}){
 const rows=[['Groei',plant.groei,'grow'],['Bloei',plant.bloei,'bloom'],['Oogst',[...plant.oogstTijd,...plant.extraOogstTijd],'harvest'],['Snoei',plant.snoeiTijd,'prune'],['Rust',plant.sterf,'rest']] as const;
 return <div className="calendar"><div/><>{monthShort.map((m,i)=><b key={i}>{m}</b>)}</>{rows.map(([label,active,kind])=><div className="calendar-row" key={label}><strong>{label}</strong>{months.map(m=><i className={active.includes(m)?kind:''} key={m} title={`${label}: ${m}`}/>)}</div>)}</div>
}

function PlantDetail({plant,onClose}:{plant:Plant,onClose:()=>void}){
 return <div className="modal-backdrop" role="presentation" onClick={onClose}><article className="passport" role="dialog" aria-modal="true" aria-labelledby="plant-title" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose} aria-label="Sluiten">×</button><header><img src={photo(plant)} alt={plant.naam}/><div><span className="number">PLANT {plant.plantnummer}</span><h2 id="plant-title">{plant.naam}</h2><i>{plant.botanischeNaam}</i><div className="tag-row">{plant.functies.map(f=><span className="pill" key={f}>{functionLabels[f]||f}</span>)}</div><p>{plant.intro}</p></div></header><div className="passport-grid"><section><h3>Water & standplaats</h3><b>💧 {plant.waterOndergrens}–{plant.waterBovengrens} van 5 · ☀ {plant.zon}</b><p>{plant.waterInfo}</p><p>{plant.zonInfo}</p></section>{(plant.oogstTijd.length>0||plant.extraOogstTijd.length>0)&&<section><h3>Oogsten</h3><b>{[...plant.oogstTijd,...plant.extraOogstTijd].join(', ')}</b><p>{plant.oogstMethode||plant.extraOogstMethode}</p></section>}<section><h3>Snoeien</h3><b>{plant.snoeiTijd.join(', ')||'Alleen wanneer nodig'}</b><p>{plant.snoeiMethode}</p><p>{plant.snoeiInformatie}</p></section><section className="allowed"><h3>✓ Dit mag weg</h3><p>{plant.woekerToestemming}</p></section><section className="forbidden"><h3>× Dit moet blijven</h3><p>{plant.woekerVerbod}</p></section><section className="wide"><h3>Jaarkalender</h3><Calendar plant={plant}/></section>{plant.weetje&&<section className="fact wide"><h3>Wist je dat?</h3><p>{plant.weetje}</p></section>}</div></article></div>
}

export default function Home(){
 const[tab,setTab]=useState<Tab>('overzicht'); const[query,setQuery]=useState(''); const[filters,setFilters]=useState<string[]>([]); const[selected,setSelected]=useState<Plant|null>(null); const[zoneId,setZoneId]=useState(zoneData[0].id);
 const filtered=useMemo(()=>sortedPlants.filter(p=>{const text=`${p.naam} ${p.botanischeNaam} ${p.functies.join(' ')}`.toLowerCase();return text.includes(query.toLowerCase())&&(filters.length===0||filters.some(f=>p.functies.includes(f))) }),[query,filters]);
 const monthIndex=new Date().getMonth(); const month=months[monthIndex];
 const tasks=sortedPlants.flatMap(p=>{const result:{plant:Plant;type:string}[]=[];if([...p.oogstTijd,...p.extraOogstTijd].includes(month))result.push({plant:p,type:'Oogsten'});if(p.snoeiTijd.includes(month))result.push({plant:p,type:'Snoeien'});return result}).slice(0,8);
 const zone=zoneData.find(z=>z.id===zoneId) as Zone; const zonePlants=zone.planten.map(slug=>sortedPlants.find(p=>p.slug===slug)).filter(Boolean) as Plant[];
 const go=(next:Tab)=>{setTab(next);window.scrollTo({top:0,behavior:'smooth'})};
 return <main>{selected&&<PlantDetail plant={selected} onClose={()=>setSelected(null)}/>}<header className="topbar"><button className="brand" onClick={()=>go('overzicht')}><span>W</span><strong>WEENER XL</strong></button><nav aria-label="Hoofdnavigatie"><button className={tab==='overzicht'?'active':''} onClick={()=>go('overzicht')}>De tuin</button><button className={tab==='plattegrond'?'active':''} onClick={()=>go('plattegrond')}>Plattegrond</button><button className={tab==='vaktermen'?'active':''} onClick={()=>go('vaktermen')}>Vaktermen</button><button className={tab==='pdfs'?'active':''} onClick={()=>go('pdfs')}>Drukwerk</button></nav><button className="manage" onClick={()=>go('aanpassen')}>Beheren</button></header>

 {tab==='overzicht'&&<><section className="hero"><div><p className="eyebrow">DE GROENE PLEK VAN WEENER XL</p><h1>Leer onze tuin<br/>kennen.</h1><p className="lead">Bekijk wat er groeit, wat je deze maand kunt doen en hoe je iedere plant goed verzorgt.</p><div className="hero-actions"><button onClick={()=>document.getElementById('planten')?.scrollIntoView({behavior:'smooth'})}>Zoek een plant</button><button className="secondary" onClick={()=>go('plattegrond')}>Bekijk de plattegrond</button></div></div><button className="map-card" onClick={()=>go('plattegrond')}><img src="/plattegrond.svg" alt="Plattegrond van de tuin van Weener XL"/><span>Ontdek waar alles groeit →</span></button></section><section className="stats"><div><b>25</b><span>planten in de tuin</span></div><div><b>28</b><span>plekken op de kaart</span></div><div><b>{tasks.length}</b><span>taken voor {month.toLowerCase()}</span></div></section><section className="now"><div className="section-head"><div><p className="eyebrow">WAT KAN IK NU DOEN?</p><h2>{month} in de tuin</h2></div></div><div className="task-grid">{tasks.length?tasks.map(({plant,type})=><button key={`${plant.slug}-${type}`} onClick={()=>setSelected(plant)}><span>{type==='Oogsten'?'●':'✂'}</span><div><b>{plant.naam}</b><small>{type}</small></div><strong>→</strong></button>):<p>Deze maand staan er geen oogst- of snoeitaken in het boekje.</p>}</div></section><section className="library" id="planten"><div className="section-head"><div><p className="eyebrow">PLANTENBIBLIOTHEEK</p><h2>Wat groeit hier?</h2></div><label className="search"><span>⌕</span><input aria-label="Zoek een plant" placeholder="Zoek op naam of soort…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="filters">{functions.map(f=><button className={filters.includes(f)?'selected':''} key={f} onClick={()=>setFilters(prev=>prev.includes(f)?prev.filter(x=>x!==f):[...prev,f])}>{functionLabels[f]}</button>)}{(filters.length>0||query)&&<button className="clear" onClick={()=>{setFilters([]);setQuery('')}}>Wis filters</button>}</div><p className="results">{filtered.length} planten gevonden</p><div className="plant-grid">{filtered.map(p=><article className="plant-card" key={p.slug} onClick={()=>setSelected(p)}><img src={photo(p)} alt={p.naam}/><div><div className="tag-row">{p.functies.slice(0,2).map(f=><span className="pill" key={f}>{functionLabels[f]||f}</span>)}</div><h3>{p.naam}</h3><i>{p.botanischeNaam}</i><p>{p.intro}</p><button onClick={()=>setSelected(p)}>Bekijk plantenpaspoort →</button></div></article>)}</div></section></>}

 {tab==='plattegrond'&&<section className="workspace map-workspace"><p className="eyebrow">INTERACTIEVE PLATTEGROND</p><h1>Waar groeit wat?</h1><p className="lead">Kies een nummer of letter en bekijk welke planten op die plek staan.</p><div className="map-layout"><div className="large-map"><img src="/plattegrond.svg" alt="Plattegrond van de tuin"/></div><aside><div className="zone-buttons">{zoneData.map(z=><button className={z.id===zoneId?'selected':''} onClick={()=>setZoneId(z.id)} key={z.id}>{z.label}</button>)}</div><div className="zone-result"><span className="pill">{zone.soort==='bak'?'PLANTENBAK':zone.soort==='vrij'?'VRIJE GROND':'HEESTER OF BOOM'}</span><h2>Plek {zone.label}</h2><p>{zonePlants.length} {zonePlants.length===1?'plant':'planten'} op deze plek</p>{zonePlants.map(p=><button className="zone-plant" onClick={()=>setSelected(p)} key={p.slug}><img src={photo(p)} alt=""/><span><b>{p.naam}</b><small>{p.intro}</small></span><strong>→</strong></button>)}</div></aside></div></section>}

 {tab==='vaktermen'&&<section className="workspace"><p className="eyebrow">KORTE UITLEG</p><h1>Tuinwoorden zonder gedoe.</h1><p className="lead">Handig wanneer je een woord in een plantenpaspoort nog niet kent.</p><dl className="terms">{[['Oogsten','Vruchten, bladeren of bloemen van de plant halen om te gebruiken.'],['Snoeien','Takken of bladeren van een plant afknippen.'],['Halfschaduw','Een plek met een deel van de dag zon en een deel schaduw.'],['Uitloper','Een lange stengel waaraan een nieuwe plant kan groeien.'],['Meerjarig','De plant leeft langer dan één jaar en komt elk jaar terug.'],['Woekeren','Snel groeien en veel ruimte innemen van andere planten.']].map(([term,text])=><div key={term}><dt>{term}</dt><dd>{text}</dd></div>)}</dl></section>}

 {tab==='aanpassen'&&<section className="workspace"><p className="eyebrow">BEHEEROMGEVING</p><h1>Houd de tuin actueel.</h1><p className="lead">Voeg planten toe, pas informatie aan of werk de plattegrond bij.</p><div className="action-grid"><button><span>＋</span><b>Nieuwe plant</b><small>Naam, foto en verzorging toevoegen</small></button><button><span>✎</span><b>Plantgegevens wijzigen</b><small>Teksten en seizoenen bijwerken</small></button><button><span>⌖</span><b>Plattegrond aanpassen</b><small>Planten plaatsen of verplaatsen</small></button></div><div className="edit-list"><h2>25 planten beheren</h2>{sortedPlants.map(p=><div key={p.slug}><img src={photo(p)} alt=""/><span><b>{p.naam}</b><small>{p.botanischeNaam}</small></span><button>Bewerken</button></div>)}</div></section>}

 {tab==='pdfs'&&<section className="workspace"><p className="eyebrow">DRUKWERK</p><h1>Altijd een actuele versie.</h1><p className="lead">Download documenten opnieuw wanneer een exemplaar beschadigd is of informatie is gewijzigd.</p><div className="pdf-list"><a href="/pdf/plantenboekje.pdf" download><span>PDF</span><div><b>Compleet plantenboekje</b><small>38 pagina’s · alle plantenpaspoorten</small></div><strong>Download ↓</strong></a><a href="/pdf/plattegrond.pdf" download><span>PDF</span><div><b>Plattegrond met plantenindex</b><small>Voor print op locatie</small></div><strong>Download ↓</strong></a><a href="/pdf/handleiding.pdf" download><span>PDF</span><div><b>Handleiding plantenbordjes</b><small>A4, klaar om opnieuw te printen</small></div><strong>Download ↓</strong></a></div><div className="notice"><b>Nieuwe informatie toegevoegd?</b><p>Na het opslaan kan hier automatisch een nieuwe drukversie worden klaargezet.</p><button>Nieuwe PDF’s maken</button></div></section>}
 </main>
}
