'use client';
import { useMemo, useState } from 'react';

const plants = [
  { name:'Aardbei', latin:'Fragaria × ananassa', tag:'Fruit', image:'/fotos/aardbei.jpg', intro:'Zoete rode vruchten en witte bloemen voor bijen.', water:'Regelmatig', sun:'Zon' },
  { name:'Bieslook', latin:'Allium schoenoprasum', tag:'Kruid', image:'/fotos/bieslook.jpg', intro:'Frisse uiensmaak en paarse, eetbare bloemen.', water:'Gemiddeld', sun:'Zon / halfschaduw' },
  { name:'Citroenmelisse', latin:'Melissa officinalis', tag:'Kruid', image:'/fotos/citroenmelisse.jpg', intro:'Geurige blaadjes voor thee en geliefd bij bijen.', water:'Gemiddeld', sun:'Zon / halfschaduw' },
  { name:'Lavendel', latin:'Lavandula angustifolia', tag:'Insecten', image:'/fotos/Lavendel.jpg', intro:'Paarse bloemen, heerlijke geur en veel bestuivers.', water:'Weinig', sun:'Zon' },
  { name:'Rode bes', latin:'Ribes rubrum', tag:'Fruit', image:'/fotos/rode_bes.JPG', intro:'Heldere rode bessen in lange trosjes.', water:'Regelmatig', sun:'Zon / halfschaduw' },
  { name:'Tijm', latin:'Thymus vulgaris', tag:'Kruid', image:'/fotos/Thyme.jpg', intro:'Sterk keukenkruid dat graag warm en droog staat.', water:'Weinig', sun:'Zon' },
];
type Tab='overzicht'|'aanpassen'|'pdfs';

export default function Home(){
 const[tab,setTab]=useState<Tab>('overzicht'); const[query,setQuery]=useState(''); const[selected,setSelected]=useState(plants[0]);
 const filtered=useMemo(()=>plants.filter(p=>`${p.name} ${p.latin} ${p.tag}`.toLowerCase().includes(query.toLowerCase())),[query]);
 return <main>
  <header className="topbar"><button className="brand" onClick={()=>setTab('overzicht')}><span>W</span><strong>WEENER XL</strong></button><nav aria-label="Hoofdnavigatie"><button className={tab==='overzicht'?'active':''} onClick={()=>setTab('overzicht')}>Ontdek de tuin</button><button className={tab==='aanpassen'?'active':''} onClick={()=>setTab('aanpassen')}>Tuin aanpassen</button><button className={tab==='pdfs'?'active':''} onClick={()=>setTab('pdfs')}>Drukwerk</button></nav><button className="manage" onClick={()=>setTab('aanpassen')}>Beheren</button></header>
  {tab==='overzicht'&&<><section className="hero"><div><p className="eyebrow">DE GROENE PLEK VAN WEENER XL</p><h1>Leer onze tuin<br/>kennen.</h1><p className="lead">Bekijk wat er groeit, wanneer je kunt oogsten en hoe je iedere plant goed verzorgt.</p></div><div className="map-card"><img src="/plattegrond.svg" alt="Plattegrond van de tuin van Weener XL"/><button onClick={()=>document.getElementById('planten')?.scrollIntoView({behavior:'smooth'})}>Bekijk alle planten <b>↓</b></button></div></section><section className="stats"><div><b>22</b><span>planten in de tuin</span></div><div><b>8</b><span>eetbare soorten</span></div><div><b>12</b><span>vrienden van bij & vogel</span></div></section><section className="library" id="planten"><div className="section-head"><div><p className="eyebrow">PLANTENBIBLIOTHEEK</p><h2>Wat groeit hier?</h2></div><input aria-label="Zoek een plant" placeholder="Zoek op naam of soort…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="plant-grid">{filtered.map(p=><article className="plant-card" key={p.name} onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/><div><span className="pill">{p.tag}</span><h3>{p.name}</h3><i>{p.latin}</i><p>{p.intro}</p><button>Bekijk plant →</button></div></article>)}</div><aside className="quick"><div><span className="pill">UITGELICHT</span><h3>{selected.name}</h3><p>{selected.intro}</p></div><div><small>STANDPLAATS</small><b>☀ {selected.sun}</b></div><div><small>WATER</small><b>● {selected.water}</b></div></aside></section></>}
  {tab==='aanpassen'&&<section className="workspace"><p className="eyebrow">BEHEEROMGEVING</p><h1>Houd de tuin actueel.</h1><p className="lead">Voeg planten toe, pas informatie aan of werk de plattegrond bij.</p><div className="action-grid"><button><span>＋</span><b>Nieuwe plant</b><small>Naam, foto en verzorging toevoegen</small></button><button><span>✎</span><b>Plantgegevens wijzigen</b><small>Teksten en seizoenen bijwerken</small></button><button><span>⌖</span><b>Plattegrond aanpassen</b><small>Planten plaatsen of verplaatsen</small></button></div><div className="edit-list"><h2>Planten beheren</h2>{plants.slice(0,4).map(p=><div key={p.name}><img src={p.image} alt=""/><span><b>{p.name}</b><small>{p.latin}</small></span><button>Bewerken</button></div>)}</div></section>}
  {tab==='pdfs'&&<section className="workspace"><p className="eyebrow">DRUKWERK</p><h1>Altijd een actuele versie.</h1><p className="lead">Download documenten opnieuw wanneer een exemplaar beschadigd is of informatie is gewijzigd.</p><div className="pdf-list"><a href="/pdf/plantenboekje.pdf" download><span>PDF</span><div><b>Compleet plantenboekje</b><small>Alle informatie en plantenpaspoorten</small></div><strong>Download ↓</strong></a><a href="/pdf/plattegrond.pdf" download><span>PDF</span><div><b>Plattegrond met plantenindex</b><small>Voor print op locatie</small></div><strong>Download ↓</strong></a><a href="/pdf/handleiding.pdf" download><span>PDF</span><div><b>Handleiding plantenbordjes</b><small>A4, klaar om opnieuw te printen</small></div><strong>Download ↓</strong></a></div><div className="notice"><b>Nieuwe informatie toegevoegd?</b><p>Na het opslaan kan hier automatisch een nieuwe drukversie worden klaargezet.</p><button>Nieuwe PDF’s maken</button></div></section>}
 </main>;
}
